"""empty message

Revision ID: b197378b512c
Revises: a5eb055f6523
Create Date: 2024-04-09 12:41:49.833541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b197378b512c'
down_revision = 'a5eb055f6523'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todo_user_id', table_name='todo')
    op.create_index(op.f('ix_todo_user_id'), 'todo', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_user_id'), table_name='todo')
    op.create_index('ix_todo_user_id', 'todo', ['user_id'], unique=False)
    # ### end Alembic commands ###
